### ISSUE TITLE
[IDEA] Add progress bar to Mega download

### ISSUE THREAD

**Issue by MikeModder** [JoshuaDoes/clonehero-launcher#1]
Looking at the mega-go docs, the `DownloadFile` function has a progress attribute 
https://godoc.org/github.com/xybydy/go-mega#Mega.DownloadFile

Maybe you could tie this in with something like [progressbar](https://github.com/schollz/progressbar) to give a visual representation of the download progress.

I'm not very fluent in Go so there may be something I missed, but I thought having a progress bar would be nice.

**Comment by MikeModder** [comment]
bump

**Comment by JoshuaDoes** [comment]
I'll give it some consideration, but as it currently stands this project might end up dead in the water. I'll let you know if I take this up or not, so leaving this open for now.
